### ISSUE TITLE
[DB/QUEST] SHADOWNLANDS -> Npc multi quete multi class

### ISSUE THREAD

**Issue by Drakking666** [ShadowQcX/Last-Kingdom-Server-9.1.0.40443---BugTracker#1]
> Le mob Grunt Throg[167216],  Coordonée [52.0;55.4] donne plusieur quete de differente classe 
> ![image](https://user-images.githubusercontent.com/59938980/137984170-ba00470c-ea1c-43e0-9b9a-6e92fb0dedd2.png)
> 

**DEMANDE DE VÉRIFICATION:**
- [ ] Refaite la manipulation pour la quêtes
- [ ] Valider que la quêtes fonctionne
- [ ] Valider que le problème à été résolu

**Comment by buddyqc69** [comment]
Besoin de re-vérification, merci !
