### ISSUE TITLE
[DB/Quest] Coeur d'azeroth

### ISSUE THREAD

**Issue by Drakking666** [ShadowQcX/Last-Kingdom-Server-9.1.0.40443---BugTracker#11]
Ou?: Silithus
Description sur problème:
il faudrais ajouter :Zidormi dans les differente zone 

Comment reproduire le problème?:
sans l'epee on peux pas recupere le coeur d'azeroth 10ene de level sans up le colier a voir  ça peux etre bien de l'avoir pour faire des quete et du stuff azeroth et monter avec azerith

ID du PNJ:128607
ID de la Quêtes: 
Version client: 9.1.0 40443 frFR

**Comment by buddyqc69** [comment]
Je vais vérifier cela, merci.

**Comment by buddyqc69** [comment]
Peux tu verifier si cela fonctionne @Drakking666 ? Merci
