### ISSUE TITLE
[DB/Quest] the lion cages

### ISSUE THREAD

**Issue by Drakking666** [ShadowQcX/Last-Kingdom-Server-9.1.0.40443---BugTracker#15]
Ou?: Antre
Description sur problème:
suite de quête : [https://fr.wowhead.com/quest=59759/la-cage-au-lion](https://fr.wowhead.com/quest=59759/la-cage-au-lion)
Comment reproduire le problème?:
rend la quête précédente prendre la nouvelle quête (13/21) 
et au lieux de pouvoir prendre la quête il y a marque rendre la quête
ID du PNJ:166980
ID de la Quêtes: 59759
Version client: 9.1.0 40443 frFR
![image](https://user-images.githubusercontent.com/59938980/138610967-79c145fa-9197-4fb1-9534-0a57961588ab.png)

**Comment by buddyqc69** [comment]
Il est supposer donner qu'elle quête ?

**Comment by buddyqc69** [comment]
Problème non résolu

**Comment by buddyqc69** [comment]
`New flags: 37683208
Old flag: 37748744
`

**Comment by buddyqc69** [comment]
J'ai faite une correction, pourrais tu valider que le problème est règler? Merci, ne pas oublier de supprimer le dossier "cache" de votre avant de tester, merci !
