### ISSUE TITLE
[Vérification/Race] Demande de vérification de toutes les races

### ISSUE THREAD

**Issue by buddyqc69** [ShadowQcX/Last-Kingdom-Server-9.1.0.40443---BugTracker#16]
**Description:**
Nous aurions besoin que toutes c'est race sois vérifié et testé au complet dans les zones de départ, merci.

**Races régulières**
- [ ] Draeneï
- [ ] Elfe de la nuit
- [x] Elfe de sang
- [ ] Gnome
- [ ] Gobelin
- [ ] Humain
- [ ] Nain
- [ ] Orc
- [ ] #20
- [ ] Mort-vivant
- [ ] Tauren
- [ ] Trolls
- [ ] #19

**Races alliées**
- [ ] Elfe du vide
- [ ] #18
- [ ] Nain sombrefer
- [ ] Kultirassien
- [ ] Mécagnome
- [ ] Sacrenuit
- [ ] Tauren de Haut-Roc
- [ ] Orc Mag'har
- [ ] Troll Zandalari
- [ ] Vulpérins

**Comment by Drakking666** [comment]
Draeneï santeforge Gool start sur le vaisseau "Le Vindicaar" tu a juste a descendre pour prendre le portail pour hurlevent .

Vulpérins start orgrimmar

autre classe
Chasseur de demon :mob s'on trop haut level pour des perso level 8 peux pas pex

Chevalier de la mort  : bloque a la quete 'Comment se faire des amis et influencer ses ennemis' equiper les 2 'Eloquente de keleseth' (arme) 
attaqué une dizaine de personne avec et personne a parlé c'est petit batard.. 
quest id :12720
