### ISSUE TITLE
Quete start troll

### ISSUE THREAD

**Issue by Drakking666** [ShadowQcX/Last-Kingdom-Server-9.1.0.40443---BugTracker#24]
Ou?:Zone depart des Trolls
Description sur problème:
crée un personnage Troll chaman (voir avec les autre classe)  et faire les quete (3eme quête bug)
Comment reproduire le problème?:
je doit parler au pnj 39062 pour dire que je suis prêt a démonté le naga pour je suppose qu'il ouvre la cage. le npc a tuer es 38142 (naga)
ID du PNJ:39062
ID de la Quêtes: 24762 
Version client: 9.1.0 40443 frFR
![image](https://user-images.githubusercontent.com/59938980/140971109-94f5b376-d379-4f41-819f-cf5e5da5d77f.png)

**Comment by Drakking666** [comment]
ça va etre anusant a faire il faut le faire pour tout les classe (démoniste) Quest ID:24780

**Comment by Drakking666** [comment]
je vien de te mettre un bug github quête de départ des trolls esque tu veux que je liste tout les quête de chaque classe ou tu doit voire le npc 39062 seul lien avec tout les quêtes .
![image](https://user-images.githubusercontent.com/59938980/140974736-e28e369d-935d-4594-9e08-d7fef16afeec.png)

**Comment by buddyqc69** [comment]
j'ai déja faite cette quête par le passer, qu'est qui se passe exactement dans cette quete qui ne fonctionne pas ?
