### ISSUE TITLE
[DB/Quest] Who Lurks in the Pit

### ISSUE THREAD

**Issue by Drakking666** [ShadowQcX/Last-Kingdom-Server-9.1.0.40443---BugTracker#3]
Quete [Who Lurks in the Pit] Numero [59949] je ne peux pas continuer a faire la quete je doit monter sur le npc

VÉRIFICATION DEMANDÉ:
- [x] Refaite la manipulation pour la quêtes
- [ ] Valider que la quêtes fonctionne (ne fonctionne pas)
- [ ] Valider que le problème à été résolu

**Comment by buddyqc69** [comment]
Je vais vérifier pour une correction pour ce problème prochainement, merci

**Comment by buddyqc69** [comment]
- [ ] Refaite la manipulation pour la quêtes
- [ ] Valider que la quêtes fonctionne
- [ ] Valider que le problème à été résolu
