### ISSUE TITLE
[Classe/Spell] Paladin->Consécration

### ISSUE THREAD

**Issue by Drakking666** [ShadowQcX/Last-Kingdom-Server-9.1.0.40443---BugTracker#9]
Classe ; Paladin
Description sur problème:

Le sort [Consécration] = 26573 
Comment reproduire le problème?:
Sort de zone qui ne fait aucun dégâts de zone
Version client: 9.1.0 40443 frFR

**Comment by buddyqc69** [comment]
Résolu, merci
